# This file is a template, and might need editing before it works on your project.
# Official docker image.
image: docker:latest

services:
  - docker:dind

variables:
  IMAGE_TAG: $CI_REGISTRY_IMAGE:$CI_COMMIT_TAG
# Protected variables were not available in non-protected branch lol.
before_script:
  - docker info | grep Registr
  - echo "${CI_REGISTRY_PASSWORD}" | docker login -u "${CI_REGISTRY_USER}" --password-stdin "${CI_REGISTRY}"

build:
  stage: build
  script:
    - docker build -t seng475-sde:latest .
    - docker tag grandfleet/seng475-sde:latest grandfleet/seng475-sde:latest
    - docker push grandfleet/seng475-sde:latest
  when: manual
  tags:
    - seng475
 
release-tagged-image:
  stage: build
  script:
    - docker build -t grandfleet/seng475-sde:4.0.13 .
    - docker tag grandfleet/seng475-sde:4.0.13 grandfleet/seng475-sde:4.0.13
    - docker push grandfleet/seng475-sde:4.0.13
  only:
    - master
  when: manual
  tags:
    - seng475

