# This file is a template, and might need editing before it works on your project.
# Official docker image.
image: docker:latest

services:
  - docker:dind

variables:
  IMAGE_TAG: $CI_REGISTRY_IMAGE:$CI_COMMIT_TAG
# Protected variables were not available in non-protected branch lol.
before_script:
  - docker info | grep Registr
  - echo "${CI_REGISTRY_PASSWORD}" | docker login -u "${CI_REGISTRY_USER}" --password-stdin "${CI_REGISTRY}"

build:
  stage: build
  script:
    - docker build -t "$CI_REGISTRY_IMAGE:$CI_COMMIT_REF_SLUG" .
    - docker tag "$CI_REGISTRY_IMAGE" "$CI_REGISTRY_IMAGE:$CI_COMMIT_REF_SLUG"
    - docker push "$CI_REGISTRY_IMAGE:$CI_COMMIT_REF_SLUG"
  when: manual
 
release-tagged-image:
  stage: build
  script:
    - docker build -t grandfleet/dolwarp:v0.66 .
    - docker tag grandfleet/dolwarp:v0.66 grandfleet/dolwarp:v0.66
    - docker push grandfleet/dolwarp:v0.66
  only:
    - master
  when: manual

